package com.example.shottracker.data.local.dao

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Transaction
import androidx.room.Update
import com.example.shottracker.data.local.entity.CourseEntity
import com.example.shottracker.data.local.entity.HoleInfoEntity
import com.example.shottracker.data.local.entity.TeeEntity
import kotlinx.coroutines.flow.Flow

@Dao
interface CourseDao {
    @Query("SELECT * FROM courses ORDER BY name ASC")
    fun getAllCourses(): Flow<List<CourseEntity>>

    @Query("SELECT * FROM courses WHERE courseId = :courseId")
    suspend fun getCourseById(courseId: Long): CourseEntity?

    @Query("SELECT * FROM courses WHERE name = :name LIMIT 1")
    suspend fun getCourseByName(name: String): CourseEntity?

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertCourse(course: CourseEntity): Long

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertHolesRaw(holes: List<HoleInfoEntity>)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertTeesRaw(tees: List<TeeEntity>)

    @Update
    suspend fun updateCourse(course: CourseEntity)

    @Delete
    suspend fun deleteCourse(course: CourseEntity)

    @Query("DELETE FROM courses WHERE courseId = :courseId")
    suspend fun deleteCourseById(courseId: Long)

    /**
     * Inserts a course with its holes and tees atomically. Holes and tees come in
     * with courseId = 0; this method stamps the autogenerated course ID onto each
     * via .copy(courseId = newId) before inserting them. If any insert throws,
     * Room rolls back the entire transaction.
     */
    @Transaction
    suspend fun createCourseWithHolesAndTees(
        course: CourseEntity,
        holes: List<HoleInfoEntity>,
        tees: List<TeeEntity>,
    ): Long {
        val courseId = insertCourse(course)
        if (holes.isNotEmpty()) {
            insertHolesRaw(holes.map { it.copy(courseId = courseId) })
        }
        if (tees.isNotEmpty()) {
            insertTeesRaw(tees.map { it.copy(courseId = courseId) })
        }
        return courseId
    }
}
