package com.example.shottracker.data.local.dao

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.example.shottracker.data.local.ShotTrackerDatabase
import com.example.shottracker.data.local.entity.CourseEntity
import com.example.shottracker.data.local.entity.HoleInfoEntity
import com.example.shottracker.data.local.entity.TeeEntity
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class CourseDaoCreateCourseTest {

    private lateinit var db: ShotTrackerDatabase
    private lateinit var courseDao: CourseDao
    private lateinit var holeInfoDao: HoleInfoDao
    private lateinit var teeDao: TeeDao

    @Before
    fun setUp() {
        val ctx = ApplicationProvider.getApplicationContext<android.content.Context>()
        db = Room.inMemoryDatabaseBuilder(ctx, ShotTrackerDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        courseDao = db.courseDao()
        holeInfoDao = db.holeInfoDao()
        teeDao = db.teeDao()
    }

    @After
    fun tearDown() {
        db.close()
    }

    @Test
    fun createCourseWithHolesAndTees_persistsAllRows() = runTest {
        val course = CourseEntity(name = "Townsend Ridge", city = "Townsend", state = "MA")
        val holes = (1..18).map { n ->
            HoleInfoEntity(
                courseId = 0,
                holeNumber = n,
                par = 4,
                greenFrontLat = 42.67, greenFrontLng = -71.71,
                greenCenterLat = 42.67, greenCenterLng = -71.71,
                greenBackLat = 42.67, greenBackLng = -71.71,
            )
        }
        val tees = listOf(
            TeeEntity(courseId = 0, name = "Blue", color = null, rating = 71.5, slope = 132),
            TeeEntity(courseId = 0, name = "White", color = null, rating = 69.0, slope = 125),
        )

        val courseId = courseDao.createCourseWithHolesAndTees(course, holes, tees)

        assertTrue("courseId should be > 0", courseId > 0L)
        val storedHoles = holeInfoDao.getHolesForCourse(courseId).first()
        val storedTees = teeDao.getTeesForCourse(courseId).first()
        assertEquals(18, storedHoles.size)
        assertEquals(2, storedTees.size)
        assertTrue(storedHoles.all { it.courseId == courseId })
        assertTrue(storedTees.all { it.courseId == courseId })
        assertEquals(1, storedHoles.first { it.holeNumber == 1 }.holeNumber)
        assertEquals(42.67, storedHoles.first().greenCenterLat!!, 0.0001)
    }

    @Test
    fun createCourseWithHolesAndTees_linksHolesToNewCourseIdEvenAfterReplace() = runTest {
        // Insert an initial course with the same name. Since @Insert uses REPLACE
        // strategy, a subsequent insert with the same name + a new autoGenerated PK
        // verifies the @Transaction method correctly stamps the NEW PK onto holes
        // and tees, rather than leaving them orphaned to the old course row.
        courseDao.insertCourse(CourseEntity(name = "Same Name", city = null, state = null))

        val course = CourseEntity(name = "Same Name", city = null, state = null)
        val holes = listOf(
            HoleInfoEntity(courseId = 0, holeNumber = 1, par = 3,
                greenFrontLat = 1.0, greenFrontLng = 1.0,
                greenCenterLat = 1.0, greenCenterLng = 1.0,
                greenBackLat = 1.0,  greenBackLng = 1.0,
            )
        )
        val tees = listOf(TeeEntity(courseId = 0, name = "Red", color = null,
            rating = null, slope = null))

        val newCourseId = courseDao.createCourseWithHolesAndTees(course, holes, tees)
        val storedHoles = holeInfoDao.getHolesForCourse(newCourseId).first()
        val storedTees = teeDao.getTeesForCourse(newCourseId).first()

        assertEquals(1, storedHoles.size)
        assertEquals(1, storedTees.size)
        assertEquals(newCourseId, storedHoles[0].courseId)
        assertEquals(newCourseId, storedTees[0].courseId)
    }
}
